<a href="https://colab.research.google.com/github/rajsecrets01/Deep-Learning-Tensorflow-Keras/blob/main/10_DL_Matrix_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
revenue = np.array([[120,250,690],[160,186,150],[456,820,520]])
expenses = np.array([[10,50,90],[60,86,50],[56,82,50]])

In [5]:
profit = revenue - expenses

In [6]:
profit

array([[110, 200, 600],
       [100, 100, 100],
       [400, 738, 470]])

In [17]:
price_per_unit = np.array([100,200,300])
units = np.array([[100,200,300],[400,500,600],[800,900,880]])

In [18]:
total = np.dot(price_per_unit ,units)
total

array([330000, 390000, 414000])

In [19]:
total = np.dot(units,price_per_unit)
total

array([140000, 320000, 524000])

EXERCISE

Below is some indian companies revenues in US dollars. Using numpy can you convert this into Indian rupees? 1 USD = 75 INR


In [23]:
mat01 = np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])
mat01

array([[200, 220, 250],
       [ 68,  79, 105],
       [110, 140, 180],
       [ 80,  85,  90]])

In [24]:
mat01*75

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

Divine flowers is a flower shop that sells different type of flowers. Below is the table showing how many flowers of each type they sold in different months. Also given are the prices of one flower each. Using this find out their total sales in every month.


In [27]:
jan = np.array([[50,60,25],[10,13,5],[40,70,52]])
jan

array([[50, 60, 25],
       [10, 13,  5],
       [40, 70, 52]])

In [35]:
units_sold = np.array([[50,60,25],[10,13,5],[40,70,52]])
price_per_unit = np.array([20,30,15])
np.dot(price_per_unit, units_sold)

array([1900, 2640, 1430])